# config/packages/security.yaml
security:
    encoders:
        Symfony\Component\Security\Core\User\InMemoryUser:
            algorithm: auto

    providers:
        in_memory:
            memory:
                users:
                    username: { password: '$2y$10$3uKUA7tOWFw1BLsACrrXke5x1Lb0P5Dc9psj2z96dkT28wt4tyHRq', roles: [ 'ROLE_USER' ] }
    # ...
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            http_basic: ~
            pattern: ^/books/ # Можете указать свой путь для API
            stateless: true # API обычно stateless

    access_control:
        - { path: ^/books/createBook, roles: ROLE_USER }
        - { path: ^/books/updateBook, roles: ROLE_USER }
        - { path: ^/books/deleteBook, roles: ROLE_USER }